name: "slide_app"
version: 0.0.1
description: slide show app.
environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dev_dependencies:
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0
  # build_test: ^0.10.2